name: build

on: [push]
    

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup jdk1.11
      uses: actions/setup-java@v1
      with:
        java-version: '1.11'

    - name: Build plugin
      run: |
        chmod +x gradlew
        ./gradlew buildPlugin
