name: build

on: [push]
    

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v1

    - name: Execute Gradle task - buildPlugin
      # this action only supported on Linux
      uses: MrRamych/gradle-actions/openjdk-8@3.0
      with:
        args: buildPlugin
