name: Release
on:
  push:
    tags:
      - 'v?*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup jdk1.11
        uses: actions/setup-java@v1
        with:
          java-version: '1.11'

      - name: Build plugin
        run: |
          chmod +x gradlew
          ./gradlew buildPlugin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'build/distributions/Graphene Helper-*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}